version: '3'
services:
  soapyremote:
    # 改为自定义的
    image: ccr.ccs.tencentyun.com/karasu/stck:soapy-remote
    network_mode: host
    restart: always
    devices:
      - /dev/bus/usb
    # stdin_open: true
    # tty: true
