name: delete-untagged
on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete untagged images
        uses: actions/github-script@v6
        with:
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const respPackages = await github.request("GET /users/{username}/packages?package_type={package_type}", {
              package_type: "container",
              username: "gzzchh",
               headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            for (pack of respPackages.data) {
              const packName = pack.name;
              console.log(`delete from packages ${packName}`);
              const response = await github.request(
                `GET /users/{username}/packages/container/${packName}/versions`,
                {
                  per_page: 100,
                  packName: packName,
                  username: "gzzchh",
                }
              );
              for (version of response.data) {
                if (version.metadata.container.tags.length == 0) {
                  console.log("delete " + version.id);
                  const deleteResponse = await github.request(
                    `DELETE /users/{org}/packages/container/${packName}/versions/${version.id}`,
                    {
                      org: "gzzchh",
                    }
                  );
                  console.log("status " + deleteResponse.status);
                }
              }
            }